### ISSUE TITLE
cancel the shutdown of outllook

### ISSUE THREAD

**Issue by miaoweiwei** [Ourselp/KeepOutlookRunning#1]
Hello, I want to ask what method is used to cancel the shutdown of outllook

**Comment by Ourselp** [comment]
I can't tell you exactly because I didn't develop it, I just repload it on github to keep a save but I think you will find your answer in this file : https://github.com/Ourselp/KeepOutlookRunning/blob/master/Connect.cpp

If not try to contact Tim Eck on super user : https://superuser.com/users/78284/tim-eck , he is the one who originally develop it

**Comment by miaoweiwei** [comment]
> I can't tell you exactly because I didn't develop it, I just repload it on github to keep a save but I think you will find your answer in this file : https://github.com/Ourselp/KeepOutlookRunning/blob/master/Connect.cpp
> 
> If not try to contact Tim Eck on super user : https://superuser.com/users/78284/tim-eck , he is the one who originally develop it

Okay thank you
